### ISSUE TITLE
Admin purge cache buttons are not clearing cache entries

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi-community/strapi-plugin-rest-cache#2]
Based on the redis playground using a 3 node replication Redis "cluster": Master + 2 Slaves + 3 Sentinels

I've made the following requests:

- /api/articles
- /api/articles?populate=*
- /api/articles/1
- /api/articles/1?populate=*

And I've tested the two main buttons within the admin:

- on the list view to purge all keys
- on the entity (ID 1) view to purge all of the keys for entity

None of the keys were purged:

![image](https://user-images.githubusercontent.com/8593673/150674419-4728cd50-b5c1-4e36-b1a9-196e4ae03e6e.png)

Expectation would be the list view purge should purge all keys with a wildcard of `/api/articles*` and the entity should purge all keys with a wildcard of `/api/articles/1*`

(tested using latest master as of commit: 2adb76b3901b4f1aaac56e8bc42148a89b74bebb)

**Comment by stafyniaksacha** [comment]
We need to confirm this again, key may have seen their ttl increased instead of deleted
