### ISSUE TITLE
Cache invalidation not working when updating Content-Type or purging cache

### ISSUE THREAD

**Issue by jpizzati-uvl** [strapi-community/strapi-plugin-rest-cache#24]
First off, @stafyniaksacha thanks for this great plugin, it is very helpful.

I am also experiencing this issue. After click on Purge REST cache button nothing happens. Same issue when updating content-type, response still returns cached data. Here's my config:

![Screen Shot 2022-05-27 at 18 47 23](https://user-images.githubusercontent.com/95911884/170743350-c186f623-12cc-4201-abd7-30cc582b597e.png)

I'm on Strapi v4.1.12

**Comment by jsanta** [comment]
Seems to be related with #23

**Comment by jpizzati-uvl** [comment]
As per my comment [here](https://github.com/strapi-community/strapi-plugin-rest-cache/issues/23#:~:text=It%27s%20working%2C%20I%20rolled%20back%20modifications%20to%20my%20controller%20and%20made%20request%20on%20the%20from%20nextjs%20app%3A), cache clearing mechanism is working as expected.

See more details on [#23](https://github.com/strapi-community/strapi-plugin-rest-cache/issues/23)
