### ISSUE TITLE
Remove trailing slashes from cache keys

### ISSUE THREAD

**Issue by gfragioud** [strapi-community/strapi-plugin-rest-cache#45]
strapi-plugin-rest-cache: v4.2.6

**Description**
Requested url is used as key for the cache. But the same request with and without trailing slash lead to 2 seperate cache entries. When you update the collection/entry only the url without trailing slashes is purged.

**Screenshot**
![image](https://user-images.githubusercontent.com/2271951/217228606-e7635a9e-1def-474a-8ac4-e2da509b790b.png)

**Proposed solution**
Trailing slashes should be removed from the requested url before use it as key.

**Comment by molund** [comment]
I just ran into a related issue where the 
`strapi.plugins["rest-cache"].services.cacheStore.clearByUid()` method ignores all the keys that contain the trailing slash.
