### ISSUE TITLE
Strapi-plugin-rest-cache with memory provider causing missing thumbnail URLs in API responses

### ISSUE THREAD

**Issue by Ketizsingh** [strapi-community/strapi-plugin-rest-cache#49]
I have installed Strapi-plugin-rest-cache with memory provider, which has significantly improved the performance of my website. However, I have noticed that some of the thumbnail URLs are missing in the API responses when the cache is used. I am also using the Strapi-plugin-populate-deep plugin, which may be related to this issue.

I have tried disabling the plugins one at a time to see if the issue persists, but I have not been able to determine the root cause. I believe there may be an issue with how these plugins handle caching or retrieving data.

Can someone please investigate this issue and provide a solution? It would be great to continue using these plugins to improve the performance of my website while ensuring that all necessary data is available in the API responses.

Thank you.

**Comment by stafyniaksacha** [comment]
Hi @Ketizsingh, do you have same issue with [4.2.6](https://github.com/strapi-community/strapi-plugin-rest-cache/releases/tag/v4.2.6)

**Comment by Ketizsingh** [comment]
I haven't tried that yet, and I only used the v4.2.7On Apr 17, 2023, at 6:13 PM, Sacha Stafyniak ***@***.***> wrote:﻿
Hi @Ketizsingh, do you have same issue with 4.2.6

**Comment by Ketizsingh** [comment]
I have tested Release v4.2.6, but the problem persists. Thumbs are still not available.

**Comment by Ketizsingh** [comment]
The code `populate[Thumbnail][fields][0]=url,height,width` is not functioning as intended. However, the alternative code `populate[Thumbnail][fields]=url,height,width` works properly. Nonetheless, using this alternative code displays all data under Thumbnail, making filtering difficult.

**Comment by Ketizsingh** [comment]
I'm closing this comment as I was able to fix the issue by removing the [0], which worked for me. However, it should still be addressed because it is now difficult to filter the values. The response size has also more than doubled, but the plugin is still functioning perfectly.
