### ISSUE TITLE
maxAge on memory provider seems wrong

### ISSUE THREAD

**Issue by mercuriete** [strapi-community/strapi-plugin-rest-cache#53]
in this line
https://github.com/strapi-community/strapi-plugin-rest-cache/blob/0f47f3b9edb934907f12ae9f7e11f7829b986ec0/packages/strapi-provider-rest-cache-memory/lib/MemoryCacheProvider.js#L27

the value ttl is divided by 1000.

So if maxAge is set to 3600, ttl is 3.6 and passed to library called: "cache-manager" that expects ttl in millis.

So I want to setup 3600 secs but ends up being divided instead of multiplied.

I am wrong?

I wil do a PR tomorrow fixing the division to multiplication.

Thanks.

**Comment by mercuriete** [comment]
@stafyniaksacha gently ping.
Is this repo unmantained?

**Comment by lyca** [comment]
node-cache-manger in version 3.6.0 uses node-lru-cache in version 6.0.0. There was a breaking change in version 4.0.0 with 7.0.0 which switched from configuration in seconds to configuration in milliseconds.
And as rest-cache plugin is using ms they must be divided by 1000. Only the default values in the methods are confusing, but they are ignored as those methods are always called with concrete values.

**Comment by derrickmehaffy** [comment]
> node-cache-manger in version 3.6.0 uses node-lru-cache in version 6.0.0. There was a breaking change in version 4.0.0 with 7.0.0 which switched from configuration in seconds to configuration in milliseconds. And as rest-cache plugin is using ms they must be divided by 1000. Only the default values in the methods are confusing, but they are ignored as those methods are always called with concrete values.

Ahhh that would explain it. We have a PR to change the `/` to `*` but I need to do a bit of testing first and see if we can easily detect which version of node-lru-cache is being used.

**Comment by derrickmehaffy** [comment]
Will set this one as closed as mentioned in the PR we haven't updated the packages that made this change yet but I've added notes to the code that when we do update we will need to change the calculation.

I plan on completely rewriting the docs to make things more clear as well.
