### ISSUE TITLE
Routes not register on @strapi/strapi@4.11.7

### ISSUE THREAD

**Issue by themaxaboy** [strapi-community/strapi-plugin-rest-cache#59]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `strapi-plugin-rest-cache@4.2.7` for the project I'm working on.

At the release v4.11.7 
- [core:strapi] Return routes once only (https://github.com/strapi/strapi/pull/17290) **listRoutes() is fixed.**
- Fix command not mounting the routes correctly (https://github.com/strapi/strapi/pull/17396) **It's already changed.**

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/strapi-plugin-rest-cache/server/utils/config/routeExists.js b/node_modules/strapi-plugin-rest-cache/server/utils/config/routeExists.js
index 9f4da8c..8eeb51e 100644
--- a/node_modules/strapi-plugin-rest-cache/server/utils/config/routeExists.js
+++ b/node_modules/strapi-plugin-rest-cache/server/utils/config/routeExists.js
@@ -13,7 +13,7 @@
  */
 function routeExists(strapi, route) {
   // check api routes
-  const match = strapi.server.listRoutes().find(
+  const match = strapi.server.mount().listRoutes().find(
     (routeLayer) =>
       routeLayer.methods.includes(route.method) &&
       routeLayer.path.match(new RegExp(`^${route.path}/?`)) // match with optional leading slash
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by derrickmehaffy** [comment]
Yeah we will need to find a way to make sure this works on 4.11.7+ and previous versions so we can't do the hard swap but I'll chat with @alexandrebodin tomorrow and see if this was even intended as it's a bit of a breaking change from our side (unless there is a better way to grab the routes)

**Comment by derrickmehaffy** [comment]
It's not ideal but the best way (for now until I rewrite some core pieces about how we actually register the middlewares) is being worked on here:

https://github.com/strapi-community/strapi-plugin-rest-cache/blob/cf39ac0defa754feca235f8dc1dc47339d284b08/packages/strapi-plugin-rest-cache/server/utils/config/routeExists.js#L14-L28
