### ISSUE TITLE
Caching not only 'factory' content types

### ISSUE THREAD

**Issue by laszlo-san** [strapi-community/strapi-plugin-rest-cache#68]
### Discussed in https://github.com/strapi-community/strapi-plugin-rest-cache/discussions/29

<div type='discussions-op-text'>

<sup>Originally posted by **niddu85** September 28, 2022</sup>
Hello,
I'm trying to cache results from strapi-plugin-navigation but I'm not able to properly configure the cache plugin since it needs the content type name to cache (eg api::button.button )
Is there anyone that was able to configure it properly?</div>

On top of this discussion is there a way to get content types created by plugins to be cached?

I am also interested in the specific navigation plugin and rest cache interaction, but if someone has a more generic solution also for all kinds of content types (or costum routes created by strapi cli) that would be highly appriciated!

Just for discussions sake the content types generated by this specific plugin are:
- `plugin::navigation.audiance`
- `plugin::navigation.navigation`
- `plugin::navigation.navigation-item`
- `plugin::navigation.navigation-item-related`

And the route I am specifically interested in: `/api/navigation/render/:uid`

Seting up 
the stragegy like
`      strategy: {
        contentTypes: [    
         {
            contentType: 'plugin::navigation.navigation',
            routes: [{ path: '/api/navigation/render/:uid', method: 'GET' }],
          },
          .....
         ]}
`

or
`
       strategy: {
        contentTypes: [    
         'plugin::navigation.navigation',
          .....
         ]}
`

did nothing sadly.

It is totally fine if this is a feature request, but if this should work even now than I think the documentation should cover this.

**Comment by Boegie19** [comment]
Looking at the code and current documentation this should work.

**Comment by garionberg** [comment]
@laszlo-san Your path is _almost_ correct, but the navigation plugin is registering the path slightly differently: `/api/navigation/render/:idOrSlug`

It seems to work when using the exact path that the navigation plugin registers or a regex that matches that path.

`config/plugins.js`
```
strategy: {
  contentTypes: [
    {
      contentType: 'plugin::navigation.navigation',
      routes: [
        {
          path: '/api/navigation/render/:idOrSlug',
          method: 'GET',
        }
      ],
    }
  ]
}
```

**Comment by laszlo-san** [comment]
@garionberg You are right!
Thank you, everything works as it should, closing this as it was user error on my side.
