### ISSUE TITLE
Cannot purge in Windows

### ISSUE THREAD

**Issue by Naahtec** [strapi-community/strapi-plugin-rest-cache#71]
Cache keys are generated incorrectly when deploying strapi in Windows. When I use the purge button, the key is not matched and therefore the cache for the REST entry is never purged.

https://github.com/strapi-community/strapi-plugin-rest-cache/blob/b5d00c80f10f582242bde8377e16e36db0f744f4/packages/strapi-plugin-rest-cache/server/utils/keys/generateCacheKey.js#L26

If I replace this code with this:
` const requestPath = toLower(ctx.request.path).replace(
    /\/$/,
    ''
  );
`
Then the purge works fine.

**Comment by Shekhar-Zealous** [comment]
Dude, this works like charm but why don't the Strapi team handle this fix :/

**Comment by derrickmehaffy** [comment]
> Dude, this works like charm but why don't the Strapi team handle this fix :/

Because it's not owned by us this is a community package.

**Comment by Boegie19** [comment]
@Naahtec Can you show me the diffrence between the 2 keys it generate?

**Comment by Naahtec** [comment]
```javascript
const requestPath = toLower(path.normalize(ctx.request.path)).replace(
    /\/$/,
    ''
  );
  // requestPath = '\\api\\legal-pages\\37'

  const windowsRequestPath = toLower(ctx.request.path).replace(
    /\/$/,
    ''
  );
  
  //windowsRequestPath = '/api/legal-pages/37'
```

**Comment by derrickmehaffy** [comment]
hmmmm we still need to normalize the path for everyone and that shouldn't be using the windows specific pathing since it's a URL not a local filesystem path

**Comment by Naahtec** [comment]
Well, only `windowsRequestPath` works under windows. (or at least thats my assumption)
I tried the exact code in docker and that works fine.

**Comment by Boegie19** [comment]
@derrickmehaffy Think Naahtec is right we should not normalize the path we should only remove all extra / from it .

**Comment by Boegie19** [comment]
No need it is a url path not a file path so we should not normalize it.

**Comment by derrickmehaffy** [comment]
Hmmm true 🤔

**Comment by nishk02** [comment]
Facing the same issue in windows (Cache regeneration and purge issues).
Works fine in Linux, Ubuntu.
