### ISSUE TITLE
Track cache hits

### ISSUE THREAD

**Issue by pragmago** [strapi-community/strapi-plugin-rest-cache#72]
Does the middleware currently keep track of the number of hits / served responses per cached entry or content type that I could access? I previously implemented a basic module for request statistics that obviously breaks when the caching plugin is used as the requests never hit the endpoint that would typically be called by clients. 

Is there a way to determine the order of middlewares that get run before the caching middleware is executed?

**Comment by Boegie19** [comment]
@pragmago currently the cache middleware is running on a very wired layer. it runs on path but before polices and middleware.
Still we are planning to change this with the RFC.

**Comment by Boegie19** [comment]
Closing this since it can be done by custom hitpass function
