### ISSUE TITLE
Strapi Rest Cache Plugin Is Not Working

### ISSUE THREAD

**Issue by ST-Wasi** [strapi-community/strapi-plugin-rest-cache#76]
**Required System information**

- Node.js version: 18.18.2
- NPM version: 9.6.6
- Strapi version: 4.15.0
- Database: postgres
- Operating system: Windows
- Is your project Javascript or Typescript: Typescript

**Describe the bug**

I was implementing the Rest API's in the my Strapi Application but i was not satisfied with the time it taking to fetch the Database and I hosted the database RDS in amazon and the Strapi too in the same region so there is no issue related to the region it hosted but when i am trying to get it in local it also takes a lil bit more time like 2 sec for a simple images and all. So I Find in Strapi forum to use the Rest Cache Plugin But I Followed full documentation but the plugin did not start. I don't know why it is not getting started. Can anyone pls look into this matter.

**Steps to reproduce the behavior**

- Go to: https://strapi.io/blog/caching-in-strapi-with-rest-cache-plugin
- Follow The Documentation
- It Shows This In Conssole
- 
![image](https://github.com/strapi-community/strapi-plugin-rest-cache/assets/144717974/6e76befc-0aee-4cfb-a3ed-ed0e749a7cb5)

Plugin.Ts Code -:

```
export default ({ env }) => ({
  redis: {
    config: {
        connections: {
            default: {
                connection: {
                    host: '127.0.0.1',
                    port: 6379,
                    db: 0,
                },
                settings: {
                    debug: false,
                },
            },
        },
    },
},
"rest-cache": {
    config: {
        provider: {
            name: "redis",
            options: {
                max: 32767,
                connection: "default",
            },
        },
        strategy: {
            
            enableEtagSupport: true,
            logs: true,
            clearRelatedCache: true,
            maxAge: 3600000,
            contentTypes: [
                "api::popular-course.popular-course",
                {
                    contentType: "api::popular-course.popular-course",
                    maxAge: 3600000,
                    hitpass: false,
                    keys: {
                        useQueryParams: false,
                        useHeaders: ["accept-encoding"],
                    },
                    method: "GET",
                }
            ],
        },
    },
},
};
```

**Expected Behaviour:** 

![image](https://github.com/strapi-community/strapi-plugin-rest-cache/assets/144717974/853ed384-15b7-481a-b0a9-867388a518c0)

This Button Should Appear In The CMS but Its Not Getting Appeared Pls Look Into This Guys

**PLEASE LET ME KNOW IF ANY OTHER CLEARIFICATION IS REQUIRED** 

This is what i am getting after all that configuratin and by calling the api multiple times

**Comment by derrickmehaffy** [comment]
As this isn't a plugin we maintain marking as closed. Please go open an issue with the maintainer.

**Comment by lematosdev** [comment]
Same issue using strapi 4.14.0 and nodejs 18. did you find any solution?

**Comment by derrickmehaffy** [comment]
You are missing `enableAdminCTBMiddleware` as defined in the documentation: https://strapi-community.github.io/strapi-plugin-rest-cache/guide/strategy/
