### ISSUE TITLE
Problems to save data in redis database

### ISSUE THREAD

**Issue by ednilsonamaral** [strapi-community/strapi-plugin-rest-cache#92]
Hello everyone !!

I trying to add redis as cache in our Strapi Project but we wont have success.

We are using this libs:
- strapi-plugin-rest-cache (v4.2.9)
- strapi-plugin-redis (v1.1.0)
- strapi-provider-rest-cache-redis (v4.2.9)

In our config/plugins.js set up like this:
```
module.exports = ({ env }) => ({
 'import-export-entries': {
   enabled: true,
 },
 upload: {
   config: {
     provider: 'aws-s3',
     providerOptions: {
       baseUrl: env('AWS_CLOUDFRONT'),
       s3Options: {
         credentials: {
           accessKeyId: env('AWS_ACCESS_KEY_ID'),
           secretAccessKey: env('AWS_ACCESS_SECRET'),
         },
         region: env('AWS_REGION'),
         params: {
           ACL: env('AWS_ACL', 'public-read'),
           Bucket: env('AWS_BUCKET'),
         },
       },
     },
   },
 },
 seo: {
   enabled: true,
 },
 redis: {
   config: {
     connections: {
       default: {
         connection: {
           host: 'url-to-redis-server',
           port: 10755,
           username: 'default',
           password: 'passWordToRedisServer',
         },
         settings: {
           debug: true,
         },
       },
     },
   },
 },
 'rest-cache': {
   config: {
     provider: {
       name: 'redis',
       options: {
         max: 32767,
         connection: 'default',
       },
     },
     strategy: {
       enableEtagSupport: true,
       logs: true,
       clearRelatedCache: true,
       maxAge: 60000, // 1 minute
       contentTypes: [
         'api::page.page',
         'api::page-footer-v2.page-footer-v2',
         'api::page-header-v2.page-header-v2',
         'api::page-home-page.page-home-page',
         'api::page-home-page-v2.page-home-page-v2',
       ],
     },
   },
 },
});
```

And in our config/database.js set up like this:
```
module.exports = ({ env }) => ({
  connection: {
    client: 'postgres',
    connection: {
      host: process.env.DATABASE_HOST,
      port: process.env.DATABASE_PORT,
      database: process.env.DATABASE_NAME,
      user: process.env.DATABASE_USERNAME,
      password: process.env.DATABASE_PASSWORD,
      ssl: env.bool('DATABASE_SSL', false),
    },
    debug: true,
    pool: {
      min: 20,
      max: 40,
    },
  },
  redis: {
    host: 'host-redis-server',
    port: 10755,
    username: 'default',
    password: 'passWordToRedisServer',
  },
});
```

the connection to the redis database is successful

we have a log of the database being configured together with the project run, but it does not save anything in the database, it is empty

it does not even make a redis log saying whether an operation was performed or not

Is there any configuration other than the ones we made to make this lib work correctly ?

![image](https://github.com/user-attachments/assets/2ae15a15-52ba-4e85-a9a8-ad2b9bf719e4)

we are using strapi with docker and redis outside of docker

redis is even configured to accept any connections from outside, with bind 0.0.0.0 and strapi can connect to redis, as evidenced, but it does not save anything in it, it is always empty

**Comment by derrickmehaffy** [comment]
You shouldn't need redis set in your database.js file.

Are the requests your making non-authenticated? The cache plugin won't cache authenticated requests.

**Comment by ednilsonamaral** [comment]
> You shouldn't need redis set in your database.js file.
> 
> Are the requests your making non-authenticated? The cache plugin won't cache authenticated requests.

Yes, all my requests are authenticated. Any specific reason why the plugin doesn't cache authenticated content-types? Is there any setting to cache where it is authenticated?

**Comment by derrickmehaffy** [comment]
At the moment it's not possible to cache authenticated requests because the returned result may have different data depending on the user/role or other parameters. Likewise the cache would normally bypass confirming the authentication properly at the moment.

Eventually we would like to add support for caching authenticated requests but it requires significant rewriting that we the maintainers don't currently have the time for.

The cache plugin for now will only cache public requests.

**Comment by ednilsonamaral** [comment]
> At the moment it's not possible to cache authenticated requests because the returned result may have different data depending on the user/role or other parameters. Likewise the cache would normally bypass confirming the authentication properly at the moment.
> 
> Eventually we would like to add support for caching authenticated requests but it requires significant rewriting that we the maintainers don't currently have the time for.
> 
> The cache plugin for now will only cache public requests.



Okay, I understand. Thanks for the clarification.

**Comment by ednilsonamaral** [comment]
@derrickmehaffy  How can I configure my requests to be public and be able to save them in redis ?

**Comment by derrickmehaffy** [comment]
> @derrickmehaffy  How can I configure my requests to be public and be able to save them in redis ?

Set the public permissions in users permissions and don't send an authorization header. This package won't cache anything in the admin just the content-api

**Comment by derrickmehaffy** [comment]
No authorization header = a public request

**Comment by ednilsonamaral** [comment]
@derrickmehaffy I try to do what you said, but still not working.

I set up to public request, and create a custom routes.js equal we have in same files of my project..

my main router for the specific page:

```
/**
 * page-home-page router.
 */

const { createCoreRouter } = require('@strapi/strapi').factories;

module.exports = createCoreRouter('api::page-home-page.page-home-page');
```

my custom router:
```
module.exports = {
  routes: [
    {
      method: 'GET',
      path: '/page-home-page',
      handler: 'page-home-page.find',
      config: {
        find: {
          auth: false,
        },
      },
    },
  ],
};
```

![Captura de tela 2024-08-06 175035](https://github.com/user-attachments/assets/033846c5-56e9-4bc4-90ac-228ac54d9e8c)

**Comment by ednilsonamaral** [comment]
@derrickmehaffy any suggestions ? :(

**Comment by derrickmehaffy** [comment]
Custom routes aren't cached by default when specifying a content-type.

No modification to routes is needed for caching normally.

**Comment by derrickmehaffy** [comment]
I created a quick local test project on Strapi 4 and recorded a quick video showing how it's functioning:

- Video: https://www.loom.com/share/10887909c93d4903a787fb964f9a2fc7?sid=9d177d72-6893-4953-a627-8c030e114683

- Code example: https://github.com/derrickmehaffy/strapi-test-v4-rest-cache-v4

---

You can see my config here: https://github.com/derrickmehaffy/strapi-test-v4-rest-cache-v4/blob/main/config/plugins.js
And this is my custom route: https://github.com/derrickmehaffy/strapi-test-v4-rest-cache-v4/blob/main/src/api/test/routes/1-custom.js
Likewise the custom controller for the route (I was gonna do it inline but we don't usually recommend that): https://github.com/derrickmehaffy/strapi-test-v4-rest-cache-v4/blob/main/src/api/test/controllers/test.js

I would advise enabling the debug option in the rest-cache strategy config so you can confirm if the cache middlewares were properly injected. With the debug enabled you should see log messages showing you what was enabled. Something like this:

```bash
⠸ Loading Strapi  strapi:strapi-plugin-rest-cache [STRATEGY]: CachePluginStrategy {
  strapi:strapi-plugin-rest-cache   debug: true,
  strapi:strapi-plugin-rest-cache   enableEtag: false,
  strapi:strapi-plugin-rest-cache   enableXCacheHeaders: true,
  strapi:strapi-plugin-rest-cache   enableAdminCTBMiddleware: true,
  strapi:strapi-plugin-rest-cache   resetOnStartup: false,
  strapi:strapi-plugin-rest-cache   clearRelatedCache: true,
  strapi:strapi-plugin-rest-cache   maxAge: 3600000,
  strapi:strapi-plugin-rest-cache   keysPrefix: 'rest-cache',
  strapi:strapi-plugin-rest-cache   contentTypes: [
  strapi:strapi-plugin-rest-cache     CacheContentTypeConfig {
  strapi:strapi-plugin-rest-cache       singleType: false,
  strapi:strapi-plugin-rest-cache       injectDefaultRoutes: true,
  strapi:strapi-plugin-rest-cache       maxAge: 3600000,
  strapi:strapi-plugin-rest-cache       hitpass: [Function: hitpass],
  strapi:strapi-plugin-rest-cache       keys: [CacheKeysConfig],
  strapi:strapi-plugin-rest-cache       plugin: undefined,
  strapi:strapi-plugin-rest-cache       routes: [Array],
  strapi:strapi-plugin-rest-cache       contentType: 'api::test.test',
  strapi:strapi-plugin-rest-cache       relatedContentTypeUid: [Array]
  strapi:strapi-plugin-rest-cache     }
  strapi:strapi-plugin-rest-cache   ],
  strapi:strapi-plugin-rest-cache   keys: CacheKeysConfig { useHeaders: [], useQueryParams: true }
  strapi:strapi-plugin-rest-cache } +0ms
⠼ Loading Strapi[2024-08-13 16:35:29.162] info: REST Cache provider "redis": connection established
  strapi:strapi-plugin-rest-cache [REGISTER] api::test.test routes middlewares +0ms
  strapi:strapi-plugin-rest-cache [REGISTER] GET /api/tests/custom/hello recv maxAge=3600000 +1ms
  strapi:strapi-plugin-rest-cache [REGISTER] POST /api/tests purge +0ms
  strapi:strapi-plugin-rest-cache [REGISTER] DELETE /api/tests/:id purge +0ms
  strapi:strapi-plugin-rest-cache [REGISTER] PUT /api/tests/:id purge +0ms
  strapi:strapi-plugin-rest-cache [REGISTER] GET /api/tests recv maxAge=3600000 +0ms
  strapi:strapi-plugin-rest-cache [REGISTER] GET /api/tests/:id recv maxAge=3600000 +0ms
  strapi:strapi-plugin-rest-cache [REGISTER] admin routes middlewares +0ms
  strapi:strapi-plugin-rest-cache [REGISTER] POST /content-manager/single-types/:model/actions/publish purge-admin +0ms
  strapi:strapi-plugin-rest-cache [REGISTER] POST /content-manager/single-types/:model/actions/unpublish purge-admin +0ms
  strapi:strapi-plugin-rest-cache [REGISTER] POST /content-manager/collection-types/:model purge-admin +0ms
  strapi:strapi-plugin-rest-cache [REGISTER] POST /content-manager/collection-types/:model/:id/actions/publish purge-admin +1ms
  strapi:strapi-plugin-rest-cache [REGISTER] POST /content-manager/collection-types/:model/:id/actions/unpublish purge-admin +0ms
  strapi:strapi-plugin-rest-cache [REGISTER] POST /content-manager/collection-types/:model/actions/bulkDelete purge-admin +0ms
  strapi:strapi-plugin-rest-cache [REGISTER] PUT /content-manager/single-types/:model purge-admin +0ms
  strapi:strapi-plugin-rest-cache [REGISTER] PUT /content-manager/collection-types/:model/:id purge-admin +0ms
  strapi:strapi-plugin-rest-cache [REGISTER] DELETE /content-manager/single-types/:model purge-admin +0ms
  strapi:strapi-plugin-rest-cache [REGISTER] DELETE /content-manager/collection-types/:model/:id purge-admin +0ms
[2024-08-13 16:35:29.167] info: Using REST Cache plugin with provider "redis"
```

**Comment by derrickmehaffy** [comment]
PS: I would **STRONGLY** advise you **don't us**e populate-deep, we removed it from the Strapi marketplace because of how bad it can be for performance (which I assume is why you are wanting to cache).

**Comment by ednilsonamaral** [comment]
solved! after watched your video demonstration I saw a few configs to set up and now Its working! Thank you so much!! :)
