### ISSUE TITLE
maxAge = 3600000 (41 days) is not a sensible default value

### ISSUE THREAD

**Issue by pinkasey** [strapi-community/strapi-plugin-rest-cache#98]
https://github.com/strapi-community/strapi-plugin-rest-cache/blob/main/packages/strapi-plugin-rest-cache/server/types/CacheRouteConfig.js

![image](https://github.com/user-attachments/assets/9b195cb6-f489-4910-9a01-8699c711c1bc)

In fact, it has caused me a serious bug in production.
A sensible value would be 3600, which is 1 hour, which is what I think the author has intended

**Comment by derrickmehaffy** [comment]
Max age is in Ms which 3,600,000ms is one hour.

**Comment by pinkasey** [comment]
right.

I'm sending it as response header, so that causes me troubles.
I assumed maxAge would be in seconds.
I see the code now.

**Comment by pinkasey** [comment]
I suggest you change the definition of maxAge on version 5.x.x (it is a breaking change) - to seconds instead of milliseconds.

Also -
document the units. it's [not specified in the docs](https://github.com/strapi-community/strapi-plugin-rest-cache/blob/main/docs/guide/strategy/index.md#maxage)
![image](https://github.com/user-attachments/assets/d11c61a9-6945-4c24-b568-33ceb15649ec)

(also the 2 other places where you can config it)
![image](https://github.com/user-attachments/assets/49fac4a2-6a51-4a13-84ce-2704be817be8)

**Comment by Boegie19** [comment]
TTLs are almost always in MS

**Comment by derrickmehaffy** [comment]
Yeah with the exception of DNS TTL values, in almost any other context a TTL would be in Ms not S

**Comment by pinkasey** [comment]
The field is called `maxAge`, which in the context of http (`max-age` directive in `Cache-Control`) is measured in seconds.

Honestly, when I start using any field that measures time, I try to understand what units it's expecting, I usually don't make assumptions. This time I failed.

It's your package, and if you don't want the documentation to be clear that's your choice.

**Comment by derrickmehaffy** [comment]
Documentation absolutely should be clear on this, while I don't own the package I am still one of the maintainers and completely refactoring the docs is on the todo
